const INSERT_NEW_BLOG_POST = `
    INSERT INTO 
    BLOG_POST
        (POST_ID, 
        POST_TITLE, 
        POST_DESCRIPTION, 
        CATEGORY_ID, 
        USER_ID, 
        POST_IMAGE_FILENAME, 
        POST_DATE_TIME, 
        POST_STATUS)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`;


const CHECK_USER_POST_OWNERSHIP = `
    SELECT * 
    FROM BLOG_POST 
    WHERE POST_ID = ? 
        AND USER_ID = ?
`;


const DELETE_BLOG_POST_BY_ID = `
    DELETE 
    FROM BLOG_POST 
    WHERE POST_ID = ?
`;


const UPDATE_BLOG_POST_NO_IMAGE = `
    UPDATE BLOG_POST 
    SET 
        POST_TITLE = ?, 
        POST_DESCRIPTION = ?, 
        CATEGORY_ID = ? 
    WHERE POST_ID = ? 
        AND USER_ID = ?
`;


const UPDATE_BLOG_POST_WITH_IMAGE = `
    UPDATE BLOG_POST 
    SET 
        POST_TITLE = ?, 
        POST_DESCRIPTION = ?, 
        CATEGORY_ID = ?, 
        POST_IMAGE_FILENAME = ? 
    WHERE POST_ID = ? 
        AND USER_ID = ?
`;


const DELETE_ALL_BLOG_POSTS_BY_USER_ID = `
    DELETE 
    FROM BLOG_POST 
    WHERE USER_ID = ?
`;


const GET_DISTINCT_USER_IDS_FROM_BLOG_POST = `
    SELECT 
    DISTINCT USER_ID 
    FROM BLOG_POST
`;


const GET_DISTINCT_USER_IDS_BY_CATEGORY_ID_FROM_BLOG_POST = `
    SELECT 
    DISTINCT USER_ID 
    FROM BLOG_POST 
    WHERE CATEGORY_ID = ?
`;


const GET_DISTINCT_CATEGORY_IDS_FROM_BLOG_POST = `
    SELECT 
    DISTINCT CATEGORY_ID 
    FROM BLOG_POST
`;


const GET_DISTINCT_CATEGORY_IDS_BY_USER_ID_FROM_BLOG_POST = `
    SELECT 
    DISTINCT CATEGORY_ID 
    FROM BLOG_POST 
    WHERE USER_ID = ?
`;


const GET_BLOG_POSTS_JSON_ARRAY_FOR_SEARCH = `
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT(
            'type', 'Blog Post',
            '_id', post.POST_ID,
            'postTitle', post.POST_TITLE
        )
    ) AS results
    FROM BLOG_POST AS post
    WHERE post.POST_TITLE LIKE ?
    LIMIT 5;
`;



module.exports = {
    INSERT_NEW_BLOG_POST,
    CHECK_USER_POST_OWNERSHIP,
    DELETE_BLOG_POST_BY_ID,
    UPDATE_BLOG_POST_NO_IMAGE,
    UPDATE_BLOG_POST_WITH_IMAGE,
    DELETE_ALL_BLOG_POSTS_BY_USER_ID,
    GET_DISTINCT_USER_IDS_FROM_BLOG_POST,
    GET_DISTINCT_USER_IDS_BY_CATEGORY_ID_FROM_BLOG_POST,
    GET_DISTINCT_CATEGORY_IDS_FROM_BLOG_POST,
    GET_DISTINCT_CATEGORY_IDS_BY_USER_ID_FROM_BLOG_POST,
    GET_BLOG_POSTS_JSON_ARRAY_FOR_SEARCH
}