const INSERT_NEW_BLOG_COMMENT = `
    INSERT INTO BLOG_POST_COMMENT
        (COMMENT_ID, 
        COMMENT_DESCRIPTION, 
        POST_ID, 
        COMMENT_DATE_TIME, 
        USER_ID)
    VALUES (?,?,?,?,?)
`;


const UPDATE_BLOG_COMMENT = `
    UPDATE BLOG_POST_COMMENT
    SET 
        COMMENT_DESCRIPTION = ?, 
        COMMENT_DATE_TIME = ?
    WHERE COMMENT_ID = ? 
        AND USER_ID = ?
`;


const DELETE_BLOG_COMMENT_BY_ID = `
    DELETE 
    FROM BLOG_POST_COMMENT
    WHERE COMMENT_ID = ? 
        AND USER_ID = ?
`;


const DELETE_ALL_BLOG_COMMENT_BY_USER_ID = `
    DELETE 
    FROM BLOG_POST_COMMENT 
    WHERE USER_ID = ?
`;


const DELETE_ALL_BLOG_COMMENT_BY_POST_ID = `
    DELETE 
    FROM BLOG_POST_COMMENT 
    WHERE POST_ID = ?
`;


module.exports = {
    INSERT_NEW_BLOG_COMMENT,
    UPDATE_BLOG_COMMENT,
    DELETE_BLOG_COMMENT_BY_ID,
    DELETE_ALL_BLOG_COMMENT_BY_USER_ID,
    DELETE_ALL_BLOG_COMMENT_BY_POST_ID
}