const INSERT_NEW_BLOG_LIKE = `
    INSERT INTO BLOG_POST_LIKE 
        (LIKE_ID, 
        POST_ID, 
        USER_ID)
    VALUES (?, ?, ?)
`;


const CHECK_BLOG_LIKE_BY_USER_ID_AND_POST_ID = `
    SELECT * 
    FROM BLOG_POST_LIKE
    WHERE POST_ID = ?
    AND USER_ID = ?
`;


const DELETE_BLOG_LIKE_BY_POST_ID_AND_USER_ID = `
    DELETE 
    FROM BLOG_POST_LIKE
    WHERE POST_ID = ?
        AND USER_ID = ?
`;


const DELETE_BLOG_LIKE_BY_POST_ID = `
    DELETE 
    FROM BLOG_POST_LIKE 
    WHERE POST_ID = ?
`;


const DELETE_BLOG_LIKE_BY_USER_ID = `
    DELETE 
    FROM BLOG_POST_LIKE
    WHERE USER_ID = ?
`;


module.exports = {
    INSERT_NEW_BLOG_LIKE,
    CHECK_BLOG_LIKE_BY_USER_ID_AND_POST_ID,
    DELETE_BLOG_LIKE_BY_POST_ID_AND_USER_ID,
    DELETE_BLOG_LIKE_BY_POST_ID,
    DELETE_BLOG_LIKE_BY_USER_ID
}